# Generated by Django 2.2 on 2019-04-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarusuarios',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
