# Generated by Django 2.2 on 2019-04-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basural', '0002_registrarusuarios_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarusuarios',
            name='fecha_publicacion',
        ),
    ]
